### ISSUE TITLE
PDU Session Resource Setup Response is invalid

### ISSUE THREAD

**Issue by mmailand** [hhorai/gnbsim#13]
Hello,
first thanks for this great project, it helps me quite a bit to understand 5G.
I use Open5gs as my packet core (https://github.com/open5gs/open5gs), but somehow the PDU Session Resource Setup Response  is invalid. I attached the pcap file. Please advise me how to rectify the issue.

Best regards,
Martin

[dump.pcap.gz](https://github.com/hhorai/gnbsim/files/5340429/dump.pcap.gz)

**Comment by hhorai** [comment]
Hi, @mmailand 

Thank you for using `gnbsim`.
The problem seems to be caused by PDU Session ID mismatching.
Open5gs uses 1, gnbsim uses 0. Unfortunately I have not found its
root cause, so could you share the log which is output by gnbsim.

**Comment by mmailand** [comment]
Hi, @hhorai 
thanks for your quick response. Here the log:

[gnbsim_log.txt.gz](https://github.com/hhorai/gnbsim/files/5340678/gnbsim_log.txt.gz)

**Comment by hhorai** [comment]
Thank you for the log.
I think that the problem is caused by `Configuration Update Command` from AMF.
At this moment gnbsim example program doesn't expect to receive the message.
I will implement to handle it, so please keep open this ticket.

**Comment by hhorai** [comment]
Hi, @mmailand 

I have updated my example code at hhorai/gnbsim@36c060f to handle the `Configuration Update Command` Message.
It would be very helpful if you could try the newest gnbsim.

**Comment by mmailand** [comment]
Hello @hhorai,
I tried your commit 36c060f, it looks better than before, but I now get a new error, that still indicates that the PDU Session Resource Setup Response is invalid.  

Additionally I also found this error messages in the logs:
10/10 15:11:57.044: [smf] ERROR: [imsi-208930123456789:1] No QoS flow (../src/smf/ngap-handler.c:96)
10/10 15:11:57.044: [smf] ERROR: [imsi-208930123456789:1] Cannot handle NGAP message (../src/smf/gsm-sm.c:240)

I attached all logs:
[amf.log.gz](https://github.com/hhorai/gnbsim/files/5359287/amf.log.gz)
[amf.pcap.gz](https://github.com/hhorai/gnbsim/files/5359289/amf.pcap.gz)
[gnbsim.log.gz](https://github.com/hhorai/gnbsim/files/5359291/gnbsim.log.gz)
[smf.log.gz](https://github.com/hhorai/gnbsim/files/5359293/smf.log.gz)
[smf.pcap.gz](https://github.com/hhorai/gnbsim/files/5359295/smf.pcap.gz)

Thanks for your great work.

**Comment by hhorai** [comment]
Thank you for testing gnbsim.
As the SMF says, I think that the problem is caused by QoS Flow ID mismatching.
open5gs publishes 1, but gnbsim responds 2.
I will try to fix `PDU Session Resource Setup Request` decoder.

**Comment by hhorai** [comment]
Hello again. @mmailand 

I have updated NGAP package at hhorai/gnbsim@6e653ed to fix QosFlowList encoder.
If you have time, could you please try with updated gnbsim?

Thank you.

**Comment by mmailand** [comment]
Hello,
thanks for your update. The update fixes the issue. The issue can be closed.

Thanks.

**Comment by hhorai** [comment]
I'm grad to hear that.
Thank you for you cooperation.
