### ISSUE TITLE
failed to EnableKernelGTP: listen udp 192.168.1.18:2152: bind: address already in use

### ISSUE THREAD

**Issue by rashmi-bhattad** [hhorai/gnbsim#16]
Hi,

Thank you so much for gnbsim :)
I am running it with free5gc and getting below error. Can you please help me to resolve it?

[gnbsim]2020/10/14 21:34:05.472999 example.go:232: failed to EnableKernelGTP: listen udp 192.168.1.3:2152: bind: cannot assign requested address

[free5gc_logs.txt](https://github.com/hhorai/gnbsim/files/5386459/free5gc_logs.txt)
[gnbsim_logs.txt](https://github.com/hhorai/gnbsim/files/5386460/gnbsim_logs.txt)

I am attaching free5gc logs, gnbsim logs & pcap.
Let me know if you need any other information.

With free5gc we already have gtp5g.ko kernel module installed. Do we still need to install gtp.ko for gnbsim?

I am unable to insert gtp.ko kernel module. Please see the screenshots below:

**osmo-ggsn Configuration:
  GTP Linux kernel support:			yes**

After executing "sudo make install" getting below:

libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/include'

It didn't work after updating below environment variables:

**export LD_RUN_PATH=/usr/local/lib
export LD_LIBRARY_PATH=/usr/local/lib/**

root@ubuntu:~/osmo-ggsn# find /lib/modules/`uname -r` -name gtp.ko
root@ubuntu:~/osmo-ggsn# 

I suspect that I am getting " failed to EnableKernelGTP" this error on gnbsim because gtp.ko kernel module is not present. Can you please help me to resolve this ?

![image](https://user-images.githubusercontent.com/50145241/96160266-59d7dd80-0f33-11eb-9199-7ade8d91614d.png)

![image](https://user-images.githubusercontent.com/50145241/96160757-03b76a00-0f34-11eb-88eb-f37e021f6218.png)

Thanks & Regards,
Rashmi

[example_json.txt](https://github.com/hhorai/gnbsim/files/5386518/example_json.txt)

**Comment by hhorai** [comment]
Hi, @rashmi-bhattad 

Thank you for having interest in gnbsim.
I wolud like to know whether you try to install free5gc and gnbsim on a single server or not.
In the former case, I thins it doesn't work well. They should be run on a different server.

I guess that you have installed kernel 5.0.0-23-generic which is required by gtp5g.ko.
In this case,I think you cannot find gtp.ko.

I recommend that you try to run gnbsim on a different server with default kernel version.

Best,

**Comment by hhorai** [comment]
In addition, according to the Issue #15 , gnbsim cannot make a gtpv1 packet with GTP Extension Header.
I recognize that it is a problem for gnbsim. In the near future, I would like gnbsim possible to run without gtp.ko.

**Comment by rashmi-bhattad** [comment]
Thank you so much for your reply.
Really appreciate it.

I will  try to run gnbsim on a different server with default kernel version.

Thanks,
Rashmi

**Comment by shigeki-yamano** [comment]
> I guess that you have installed kernel 5.0.0-23-generic which is required by gtp5g.ko.
> In this case,I think you cannot find gtp.ko.

In the case of Ubuntu, gtp.ko for kernel 5.0.0-23-generic is included in linux-modules-extra-5.0.0-23-generic package.
So, gtp.ko can be installed as follows.

Check if  linux-modules-extra-5.0.0-23-generic package is installed.
```
$ sudo dpkg --get-selections | grep -e generic
...
linux-modules-5.0.0-23-generic                  install
...
linux-modules-extra-5.0.0-23-generic            deinstall
```

Intall linux-modules-extra-5.0.0-23-generic
```
sudo apt install -y linux-modules-extra-5.0.0-23-generic
```

Check the path of gtp.ko.
```
$ find /lib/modules/`uname -r` -name gtp.ko
/lib/modules/5.0.0-23-generic/kernel/drivers/net/gtp.ko
```

Load gtp.ko
```
sudo modprobe udp_tunnel
sudo insmod /lib/modules/5.0.0-23-generic/kernel/drivers/net/gtp.ko
```

Unload gtp.ko
```
sudo rmmod /lib/modules/5.0.0-23-generic/kernel/drivers/net/gtp.ko
sudo modprobe -r udp_tunnel
```

**Comment by wmnsk** [comment]
> In the near future, I would like gnbsim possible to run without gtp.ko.

FYI, the `gtpv1` package supports GTPv1-U packet forwarding without the Linux kernel module. It's less performant, though.

https://github.com/wmnsk/go-gtp/tree/master/gtpv1#using-userland-gtp-u

**Comment by rashmi-bhattad** [comment]
Thank you so much Shigeki Yamano San for your reply.
I did try the steps provided by you and yes with these steps I could insert gtp module.

root@ubuntu:/home/rashmi# **modinfo gtp**
filename:       /lib/modules/5.0.0-23-generic/kernel/drivers/net/gtp.ko
alias:          net-pf-16-proto-16-family-gtp
alias:          rtnl-link-gtp
description:    Interface driver for GTP encapsulated traffic
author:         Harald Welte <hwelte@sysmocom.de>
license:        GPL
srcversion:     23A9379DDD933275B2F672B
depends:        udp_tunnel
retpoline:      Y
intree:         Y
name:           gtp
vermagic:       5.0.0-23-generic SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4
root@ubuntu:/home/rashmi# **modinfo gtp5g**
filename:       /lib/modules/5.0.0-23-generic/kernel/drivers/net/gtp5g.ko
alias:          net-pf-16-proto-16-family-gtp5g
alias:          rtnl-link-gtp5g
description:    Interface for 5G GTP encapsulated traffic
author:         Yao-Wen Chang <yaowenowo@gmail.com>
license:        GPL
srcversion:     AED568967197A7C6A60E396
depends:        udp_tunnel
retpoline:      Y
name:           gtp5g
vermagic:       5.0.0-23-generic SMP mod_unload 

root@ubuntu:/home/rashmi# **lsmod | grep gtp**
**gtp5g**                  36864  0
**udp_tunnel**             16384  1 **gtp5g**
root@ubuntu:/home/rashmi# 

Here are the interfaces on my system:


root@ubuntu:/home/rashmi# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: **ens33**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:63:d8:67 brd ff:ff:ff:ff:ff:ff
    inet 192.168.64.135/24 brd 192.168.64.255 scope global dynamic noprefixroute ens33
       valid_lft 1240sec preferred_lft 1240sec
    inet6 fe80::90d5:5a8e:19e1:fb3f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: **ens38**: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:29:63:d8:71 brd ff:ff:ff:ff:ff:ff
    inet **192.168.1.17/16** brd 192.168.255.255 scope global ens38:1
       valid_lft forever preferred_lft forever
    inet **192.168.1.18/16** brd 192.168.255.255 scope global secondary ens38:2
       valid_lft forever preferred_lft forever
6: **upfgtp**: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet6 fe80::f681:492c:3525:46ef/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
root@ubuntu:/home/rashmi# 


But, still getting the same error on gnbsim & hence, unable to pass the data.

[gnbsim]2020/10/20 17:14:42.476645 example.go:88: write: len 40, info: &{Stream:0 SSN:4 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:2222112692 CumTSN:0 AssocID:10}
[gnbsim]2020/10/20 17:14:45.477305 example.go:216: test: GTPuIFname: ens38
[gnbsim]2020/10/20 17:14:45.477413 example.go:217: test: GTP-U Peer: 192.168.1.18
[gnbsim]2020/10/20 17:14:45.477454 example.go:218: test: GTP-U Peer TEID: 1
[gnbsim]2020/10/20 17:14:45.477491 example.go:219: test: GTP-U Local TEID: 2596996162
[gnbsim]2020/10/20 17:14:45.477527 example.go:220: test: UE address: 60.60.0.1
test: gNB UDP local address: 192.168.1.3:2152
[gnbsim]2020/10/20 17:14:45.477669 example.go:232: **failed to EnableKernelGTP: listen udp 192.168.1.3:2152: bind: cannot assign requested address**
root@ubuntu:~/gnbsim/example# 


Thanks,
Rashmi

**Comment by hhorai** [comment]
@rashmi-bhattad 
Do you configure the IP address 192.168.1.3 on ens38? 
bind(2) is used to assign an IP address and port, so the IP address should be set on your host in advance.

**Comment by hhorai** [comment]
@wmnsk 
Thank you for the information. Your repository `wmnsk/gtp-go` that is really helpful for me.
I have recognized that gtp-go supports userland GTP forwarding.
And in my understanding, gtp-go doesn't support encapsulation with GTPv1 Extension Header field for now. Is it correct?
If `gtpv1` supports it, I would like to use the package for gnbsim.

**Comment by rashmi-bhattad** [comment]
> @rashmi-bhattad
> Have you configured the IP address 192.168.1.3 on ens38?
> bind(2) is used to assign an IP address and port, so the IP address should be set on your host in advance.

Hi @hhorai 

It proceeded further after configuring gnb IP addr 192.168.1.3 on ens38.
Thank you so much for your reply.

[gnbsim]2020/10/21 09:52:02.983223 example.go:120: read: timeout
[gnbsim]2020/10/21 09:52:02.983796 example.go:88: write: len 40, info: &{Stream:0 SSN:4 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:3800324475 CumTSN:0 AssocID:43}
[gnbsim]2020/10/21 09:52:05.985065 example.go:216: test: GTPuIFname: ens33
[gnbsim]2020/10/21 09:52:05.985128 example.go:217: test: GTP-U Peer: 192.168.1.18
[gnbsim]2020/10/21 09:52:05.985137 example.go:218: test: GTP-U Peer TEID: 1
[gnbsim]2020/10/21 09:52:05.985142 example.go:219: test: GTP-U Local TEID: 2596996162
[gnbsim]2020/10/21 09:52:05.985213 example.go:220: test: UE address: 60.60.0.1
test: gNB UDP local address: 192.168.1.3:2152
runUPlane
[gnbsim]2020/10/21 09:52:13.999800 example.go:397: failed to GET http://172.16.1.2:8080/: Get "http://172.16.1.2:8080/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

I think to pass data I need to run local web server. 
Please correct me if I am wrong.

Thanks,
Rashmi

**Comment by hhorai** [comment]
Hi,

Yes, you need to run local web server.
It is listen on the IP address 172.16.1.2 and port number 8080 for the configuration above.

**Comment by hhorai** [comment]
Hello, @rashmi-bhattad 

If you do not have any other questions, shall we close this issue?
I would like to update the README as a feed backup of the issue. I have already opened another ticket at #27.

**Comment by rashmi-bhattad** [comment]
@hhorai 
Yes, sure. We can close this issue. 
Thank you 👍
