### ISSUE TITLE
when MNC is 00, json.Unmarshal(bytes, p) malfunction

### ISSUE THREAD

**Issue by frankieky888** [hhorai/gnbsim#22]
gnbsim/encoding/ngap/ngap.go line 129

when I fmt.Println(p), the result as below
&{{0 0 0} []  0 { 0 0  0  {  [] [] [] [] [] [] [] [] [] [] [] []} {0  0 }   0 0 {0 0} {{false false} 0 [] [] [] 0 0 <nil>} 0 {false false} 0 0 <nil>} {{{0 0} 0} {{0 0} }}   0 {[] 0 0 <nil> 0} <nil> <nil> <nil> 0 0}

**Comment by frankieky888** [comment]
found that example.json mnc need a double quote, please correct your github file

"mnc": "00",

**Comment by hhorai** [comment]
Thank you for your interest in gnbsim.
In this case, you can set the mnc value correctly by `"mnc": 0`.
If the mnc value starts with 0, I think it is invalid for JSON format.

**Comment by frankieky888** [comment]
Now I get below error when integrating with free5gc v3.0.4, using MNC = 0. Is this probably caused by configuring MNC = 0 so the 5G AKA calculation process failed?

free5gc v3.0.4 log:
[WARN][AMF][NAS] NAS MAC verification failed(received: 0x44f84596, expected: 0x58ebcdbd) (/go/src/free5gc/src/amf/nas/nas_security/security.go:179 free5gc/src/amf/nas/nas_security.Decode)
[ERRO][AMF][Gmm] NAS message integrity check failed (/go/src/free5gc/src/amf/gmm/sm.go:225 free5gc/src/amf/gmm.SecurityMode)

gnbsim log:
  Item 2
    Protocol IE: id-NAS-PDU (38)
      IE length: 22
        EPD: 5G Mobility Management (0x7e)
        Security Header: 0x3
          mac: 13312cf3
          seq: 0
        ***** Integrity check failed...
        Received  : 13312cf3
        Calculated: 3cff1f85

**Comment by hhorai** [comment]
Thank you for reporting the problem.
It seems to be a bug in the case of `mnc < 10`.
I will fix it within a few days.

**Comment by frankieky888** [comment]
May be you need to add more code for mnc <10? now it look like plmn 99900 become 999f0 instead of 999f00

in encoding/nas line number : 1066
`func encPLMN(mcc, mnc int) (plmn [3]byte) {
	format := "%d%d"
	if mnc < 100 {
		format = "%df%d"
	}

	str := fmt.Sprintf(format, mcc, mnc)
	for i, v := range Str2BCD(str) {
		plmn[i] = v
	}
	return
}`

**Comment by frankieky888** [comment]
if mnc <10 {
	format = "%df0%d"
}

**Comment by frankieky888** [comment]
supi := fmt.Sprintf("%d%d%s", ue.MCC, ue.MNC, ue.MSIN)
changed to 
supi := fmt.Sprintf("%d%02d%s", ue.MCC, ue.MNC, ue.MSIN)

now the program run smoothly

**Comment by hhorai** [comment]
Thank you very much for your help.
Now the problem has been fixed in hhorai/gnbsim@70e5b3d.
Could you try it when you have some time?

**Comment by frankieky888** [comment]
checked and bug fixed
