### ISSUE TITLE
README.md enhancement

### ISSUE THREAD

**Issue by hhorai** [hhorai/gnbsim#27]
I would like to update the README.md page to the way to install gtp.ko mentioned by @shigeki-yamano in #16 .

**Comment by midu16** [comment]
Hey, @hhorai 

Is there any other reason for using the ```sudo``` user to run the service under?

Thnak you,
Mi

**Comment by hhorai** [comment]
Hi, @midu16 

In my understanding, gnbsim should be run as root to
- add tun device
- set UE IP address

**Comment by hhorai** [comment]
I have fixed this issue in hhorai/gnbsim@2be80c7.
