### ISSUE TITLE
failed to ADD tun device=gtp0: Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy

### ISSUE THREAD

**Issue by regek** [hhorai/gnbsim#37]
Hi Hhorai,

I keep getting the following Error

`failed to ADD tun device=gtp0: Tuntap IOCTL TUNSETIFF failed [0], errno device or resource busy`

My Topology: 

> 10.100.200.13 /udr
> 10.100.200.11 /nssf
> 10.100.200.10 /pcf
> 10.100.200.14 /smf
> 10.100.200.8 /udm
> 10.100.200.9 /ausf
> **10.100.200.12 /amf**
> 10.100.200.7 /webui
> 10.100.200.6 /nrf
> **10.100.200.2 /upfb**
> **10.100.200.4 /upf2**
> 10.100.200.3 /mongodb
> **10.100.200.5 /upf1**
>**10.100.200.1 RAN**
> VM IP: 192.168.37.136/192.168.1.16
> remote server: 192.168.1.17:8080 (there is a webserver running and it is accessible from VM)

I'm running the docker-compose configuration of free5gc. I'm not sure if the config is wrong or something else.

I've attached the config folder and gnbsim config+log

[gnbsim-config.txt](https://github.com/hhorai/gnbsim/files/5888578/gnbsim-config.txt)
[free5gc-config.zip](https://github.com/hhorai/gnbsim/files/5888573/config.zip)
[gnblogfile.txt](https://github.com/hhorai/gnbsim/files/5888565/gnblogfile.txt)

**Comment by hhorai** [comment]
Could you try `sudo ip link del gtp-gnb` before running gnbsim?

**Comment by regek** [comment]
Awesome that solved the issue. A new issue has risen
`example.go:558: failed to GET http://192.168.1.17:8080/: Get "http://192.168.1.17:8080/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

I'm guessing this is a routing issue. I did configure the destination in the uerouting.yml to 192.168.1.17. Do I need a different configuration?

Thanks

**Comment by hhorai** [comment]
I guess the server that has IP address 192.168.1.7 doesn' have the routing table for 60.0.0.0/xx. Its nexthop should be set to 192.168.1.16. You can check it by `ip route` command on the remote server.

**Comment by regek** [comment]
Thanks for the quick reply. It seems there is some sort of routing issue. Packets never reach the other machine (checked using Wireshark). In the end, I just ran the webserver on the same VM.
