### ISSUE TITLE
free5gc smf does not respond to amf when my gnbsim send PDU Session Establishment Request.

### ISSUE THREAD

**Issue by hhorai** [hhorai/gnbsim#4]
the log tested on free5gc-compose.
```
amf              | DEBU[2020-07-02T15:38:33Z]/go/src/free5gc/src/amf/gmm/handler.go:329 free5gc/src/amf/gmm.selectSmf() Search SMF from NRF[https://nrf:29510]        AMF=Gmm
nrf              | 2020/07/02 15:38:33 {"mcc":"208","mnc":"93"}
nrf              | 2020/07/02 15:38:33 map[$and:[map[nfType:SMF] map[$or:[map[allowedNfTypes:AMF] map[allowedNfTypes:map[$exists:false]]]] map[nfServices:map[$elemMatch:map[nfServiceStatus:REGISTERED serviceName:map[$in:[nsmf-pdusession]]]]] map[$or:[map[plmnList:map[$elemMatch:map[mcc:208 mnc:93]]]]] map[$or:[map[sNssais:map[$elemMatch:map[sd:010203 sst:1]]] map[sNssais:map[$exists:false]]]] map[smfInfo.sNssaiSmfInfoList:map[$elemMatch:map[dnnSmfInfoList:map[$elemMatch:map[dnn:internet]]]]]]]
amf              | 2020/07/02 15:38:33 timer closed
nrf              | [GIN] 2020/07/02 - 15:38:33 | 200 |    2.859502ms |   10.100.200.14 | GET      /nnrf-disc/v1/nf-instances?dnn=internet&requester-nf-type=AMF&service-names=nsmf-pdusession&snssais=%7B%22sst%22%3A1%2C%22sd%22%3A%22010203%22%7D&target-nf-type=SMF&target-plmn-list=%7B%22mcc%22%3A%22208%22%2C%22mnc%22%3A%2293%22%7D
amf              | ERRO[2020-07-02T15:38:33Z]/go/src/free5gc/src/amf/nas/handler.go:41 free5gc/src/amf/nas.HandleNAS() Send to Nas Error: server no response         AMF=NGAP
```
I think that the message which created by my gnbsim is not correct.

**Comment by hhorai** [comment]
I have tried this patch
`--- a/consumer/sm_context.go
+++ b/consumer/sm_context.go
@@ -2,6 +2,7 @@ package consumer
 
 import (
        "context"
+       "fmt"
        "free5gc/lib/openapi"
        "free5gc/lib/openapi/Nsmf_PDUSession"
        "free5gc/lib/openapi/models"
@@ -53,6 +54,7 @@ func SendCreateSmContextRequest(ue *amf_context.AmfUe, smfUri string, nasPdu []b
        postSmContextsRequest.JsonData = &smContextCreateData
        postSmContextsRequest.BinaryDataN1SmMessage = nasPdu
 
+       fmt.Printf("GNBSIM: SendCreateSmContextRequest: %+v\n", postSmContextsRequest)
        postSmContextReponse, httpResponse, err := client.SMContextsCollectionApi.PostSmContexts(context.Background(), postSmContextsRequest)
        if err == nil {
                response = &postSmContextReponse
@@ -71,7 +73,10 @@ func SendCreateSmContextRequest(ue *amf_context.AmfUe, smfUri string, nasPdu []b
                        problemDetail = &problem
                }
        } else {
-               err1 = openapi.ReportError("server no response")
+               // GNBSIM
+               openapi.ReportError("server no response")
+               err1 = err
+               //err1 = openapi.ReportError("server no response")
        }
        return
 }
`
The output is as follow.
`
amf              | ERRO[2020-07-05T06:20:29Z]/go/src/free5gc/src/amf/nas/handler.go:41 free5gc/src/amf/nas.HandleNAS() Send to Nas Error: unsupported scheme[]       AMF=NGAP

`
free5gc amf did not send SmContextsRequest to smf. the cause is scheme field has no value. I think that the field is set to 'https'. I will continue to find the root cause.

**Comment by hhorai** [comment]
I have found that selectSmf() in AMF returns with no error and no SMF entry. The root cause is in smfcfg.conf. My configuration file has no S-NSSAI value. S-NSSAI is mandatory field for PDU Session Establishment. So mongo DB cannot find a valid SMF entry. see, hhorai@368ddf5.

**Comment by hhorai** [comment]
At this moment, free5gc says that...
```
smf              | ERRO[2020-07-10T08:20:09Z]/go/src/free5gc/src/smf/context/user_plane_information.go:387 free5gc/src/smf/context.(*UserPlaneInformation).GenerateDefaultPath() Can't find UPF with DNN [internet]            SMF=Context
smf              | ERRO[2020-07-10T08:20:09Z]/go/src/free5gc/src/smf/context/user_plane_information.go:180 free5gc/src/smf/context.GenerateDataPath() invalid path                                  SMF=Context
smf              | ERRO[2020-07-10T08:20:09Z]/go/src/free5gc/src/smf/producer/pdu_session.go:148 free5gc/src/smf/producer.HandlePDUSessionSMContextCreate() Path for serve DNN[internet] not found        SMF=pdu_session
smf              | [GIN] 2020/07/10 - 08:20:09 | 403 |   396.42677ms |   10.100.200.14 | POST     /nsmf-pdusession/v1/sm-contexts
amf              | 2020/07/10 08:20:09 timer closed
amf              | GNBSIM: RES: &http.Response{Status:"403 Forbidden", StatusCode: 403, Proto:"HTTP/2.0", ProtoMajor: 2, ProtoMinor: 0, Header:http.Header{"Content-Length":[]string{"326"}, "Content-Type":[]string{"multipart/related; boundary=\"d24c900b3f418307f55efd582b3d48905961cbde45ed8e6598692c3aee1a\""}, "Date":[]string{"Fri, 10 Jul 2020 08:20:09 GMT"}}, Body:http2.transportResponseBody{cs:(*http2.clientStream)( 0xc000824580)}, ContentLength: 326, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)( 0xc0000eab00), TLS:(*tls.ConnectionState)( 0xc000866160)}
amf              | GNBSIM: RES body: --d24c900b3f418307f55efd582b3d48905961cbde45ed8e6598692c3aee1a
amf              | Content-Type: application/json
amf              |
amf              | {"error":{"title":"DNN Not Supported","status":403,"detail":"The DNN is not supported by the SMF.","cause":"DNN_NOT_SUPPORTED"},"n1SmMsg":{"contentId":"N1Msg"}}
amf              | --d24c900b3f418307f55efd582b3d48905961cbde45ed8e6598692c3aee1a--
amf              |
amf              | INFO[2020-07-10T08:20:09Z]/go/src/free5gc/src/amf/gmm/handler.go:211 free5gc/src/amf/gmm.HandlePDUSessionEstablishmentRequest() smfUri: https://smf:29502                     AMF=Gmm
amf              | WARN[2020-07-10T08:20:09Z]/go/src/free5gc/src/amf/gmm/handler.go:225 free5gc/src/amf/gmm.HandlePDUSessionEstablishmentRequest() PDU Session Establishment Request is rejected by SMF[pduSessionId:1]  AMF=Gmm
amf              | INFO[2020-07-10T08:20:09Z]/go/src/free5gc/src/amf/gmm/message/send.go:17 free5gc/src/amf/gmm/message.SendDLNASTransport() [NAS] Send DL NAS Transport                   AMF=Gmm
amf              | INFO[2020-07-10T08:20:09Z]/go/src/free5gc/src/amf/nas/nas_security/security.go:37 free5gc/src/amf/nas/nas_security.Encode() NasPdu Security: Integrity Protected And Ciphered  AMF=NAS
amf              | INFO[2020-07-10T08:20:09Z]/go/src/free5gc/src/amf/ngap/message/send.go:138 free5gc/src/amf/ngap/message.SendDownlinkNasTransport() [AMF] Send Downlink Nas Transport             AMF=NGAP
```

**Comment by tim-ywliu** [comment]
@hhorai 

Please check my response in [https://github.com/free5gc/free5gc-compose/issues/9](url)

**Comment by hhorai** [comment]
Thank you very much for your help.
Now I can see the pfcp Association Setup Response from UPF.
I will report the detail for that issue in free5gc/free5gc-compose#9.

**Comment by hhorai** [comment]
I have posted the root cause for this issue in free5gc/free5gc-compose#9.
Now, my gnbsim receives 'PDU Session Establishment accept' message from the AMF.
This issue hhorai/gnbsim#4 can be closed.
