### ISSUE TITLE
No Response found when Ping 60.60.0.1 from 5GC

### ISSUE THREAD

**Issue by zhangds007** [hhorai/gnbsim#43]
Hi Hhorai,
Thank you for your gnbsim. its a good tool to learn 5GC deeply. I am a newcomer to learn 5GC and gnbsim.
Here is my test env. 
PC1, free5gc,  has two IP address: 10.88.120.100 is for free5gc(AMF,UPF), 192.168.1.28 is for internet
PC2, gnbsim,  has two IP address: 10.88.120.188 is for gnbsim, 192.168.1.13 is for internet.
I run free5gc and gnbsim successfully, and one UE registers into 5GC OK and get one new IP 60.60.0.1. 
 when I ping 60.60.0.1 from PC1 5gc, it shows "No Response found" in both PC1 and PC2. I can catch ICMP packages in PC2, it shows that PING packages is coming into PC2 with GTP tunnel. but PING ACK packets can not go back to PC1. Can you help? Thanks a lot. I do not know if gnbsim issue or my pc routing issue. I also meet "context deadline exceeded" issue. maybe this issue is linked with PING no response issue.

here are some trace I collect from gnbsim
=================
[gnbsim]2021/02/14 08:54:27.754903 example.go:122: read: timeout
[gnbsim]2021/02/14 08:54:27.755052 example.go:90: write: len 40, info: &{Stream:0 SSN:4 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:749078944 CumTSN:0 AssocID:3}
[gnbsim]2021/02/14 08:54:28.762214 example.go:300: GTPuIFname: enp0s9
[gnbsim]2021/02/14 08:54:28.762243 example.go:301: GTP-U Peer: 10.88.120.100
[gnbsim]2021/02/14 08:54:28.762249 example.go:302: GTP-U Peer TEID: 1
[gnbsim]2021/02/14 08:54:28.762253 example.go:303: GTP-U Local TEID: 2596996162
[gnbsim]2021/02/14 08:54:28.762257 example.go:304: QoS Flow ID: 0
[gnbsim]2021/02/14 08:54:28.762260 example.go:305: UE address: 60.60.0.1
test: gNB UDP local address: 10.88.120.188:2152
runUPlane
[gnbsim]2021/02/14 08:54:36.772146 example.go:558: failed to GET https://github.com: Get "https://github.com": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
=================
Kernel IP routing table in PC2 with gnbsim
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.88.120.1     0.0.0.0         UG    0      0        0 enp0s9
0.0.0.0         192.168.1.1     0.0.0.0         UG    100    0        0 enp0s3
10.88.120.0     0.0.0.0         255.255.255.0   U     0      0        0 enp0s9
60.60.0.0       0.0.0.0         255.255.255.240 U     0      0        0 enp0s9
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 enp0s9
192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 enp0s3
192.168.56.0    0.0.0.0         255.255.255.0   U     101    0        0 enp0s8

==================
Kernel IP routing table in PC1 with 5GC
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.88.120.1     0.0.0.0         UG    0      0        0 eno1
0.0.0.0         192.168.1.1     0.0.0.0         UG    600    0        0 wlp3s0
10.88.120.0     0.0.0.0         255.255.255.0   U     0      0        0 eno1
60.60.0.0       0.0.0.0         255.255.255.0   U     0      0        0 upfgtp
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 eno1
192.168.1.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp3s0

**Comment by hhorai** [comment]
I guess it's a kind of a routing issue. For thinking simply, I suggest PC1 divides into different PCs. One for gnbsim, another for the www server in Data Network.

**Comment by zhangds007** [comment]
I disable enp0s3 in PC2 with gnbsim. still no response found when I ping 60.60.0.1 from PC1 with 5GC.

**Comment by hhorai** [comment]
The source IP address for `ping` should be `192.168.1.1`. Therefore  I think you cannot disable the network interface.
In my previous post, I suggested logical separation for PC2. Gnbsim and www server in the common server is very complicated to configure. I have not tried yet.

**Comment by zhangds007** [comment]
OK，I will try to reinstall my virtual machine for PC2 later.
