### ISSUE TITLE
Decoding of slice information PDUSessionResourceSetupRequest  

### ISSUE THREAD

**Issue by orion-belt** [hhorai/gnbsim#46]
@hhorai 
I am trying to use gnbsim with OAI 5G core. I getting trouble to decode slice defferentiator in PDUSessionResourceSetupRequest message.

It will be great if you give some hint for handle decoding.

[pdu_session_accept_sd_decoding.zip](https://github.com/hhorai/gnbsim/files/6091067/pdu_session_accept_sd_decoding.zip)

```
Procedure Code: id-PDUSessionResourceSetup (29)
PDU Length: 155
Protocol IEs: 3 items
  Item 0
    Protocol IE: id-AMF-UE-NGAP-ID (10)
      IE length: 2
  Item 1
    Protocol IE: id-RAN-UE-NGAP-ID (85)
      IE length: 2
  Item 2
    Protocol IE: id-PDUSessionResourceSetupListSUReq (74)
      IE length: 128
number of sequence: 136
          PDU Session ID: 64
          S-NSSAI
            SST: 10
          PDU Session Resource Setup Request Transfer
          Protocol IEs: 57067 items
            Item 0
[gnbsim]2021/03/05 13:59:29.727732 ngap.go:708: Unsupported Protocol IE: 31134
              Protocol IE:  (31134)
                IE length: 126
panic: runtime error: slice bounds out of range [126:119]

goroutine 9 [running]:
github.com/hhorai/gnbsim/encoding/ngap.readPduByteSlice(...)
	/gnbsim/encoding/ngap/ngap.go:2010
```

**Comment by hhorai** [comment]
Thank you for reporting the problem. It is a bug for gnbsim.
The root cause has already been found. I am considering how it is fixed.

**Comment by hhorai** [comment]
I have fixed the problem in 7e45599.
Could you try the newest version of gnbsim for your test?

**Comment by orion-belt** [comment]
Thanks. It is working for me I did one more change. Criticality for following IE in PDUSessionResourceSetupresponse should be ignore.

id-AMF-UE-NGAP-ID 
id-RAN-UE-NGAP-ID

**Comment by hhorai** [comment]
Thank you for testing. Now the criticalities are fixed.
