### ISSUE TITLE
Error from AMF

### ISSUE THREAD

**Issue by regek** [hhorai/gnbsim#5]
Hi,
I'm getting the following error when running the example. I'm using free5GC in docker.

`amf              | ERRO[2020-08-18T19:47:52Z]/go/src/free5gc/src/amf/nas/handler.go:42 free5gc/src/amf/nas.HandleNAS() Handle NAS Error: server no response          AMF=NGAP
`

The output from the example:
`[ngap]2020/08/18 19:55:22.931868 example.go:58: SndBufSize: 212992, RcvBufSize: 212992
[ngap]2020/08/18 19:55:22.931971 example.go:77: write: len 44, info: &{Stream:0 SSN:0 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:0 CumTSN:0 AssocID:0}
[ngap]2020/08/18 19:55:22.943730 example.go:90: read: len 53, info: &{Stream:0 SSN:0 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:3142379215 CumTSN:0 AssocID:12}
dump: 20150031000004000100050100414d4600600008000002f839cafe0000564001ff005000100002f839000110080102031008112233
Procedure Code: id-NGSetup (21)
PDU Length: 49
Protocol IEs: 4 items
  Item 0
    Protocol IE: id-AMFName (1)
      IE length: 5
        decoding id(1) not supported yet.
        dump: 0100414d46
  Item 1
    Protocol IE: id-ServedGUAMIList (96)
      IE length: 8
        decoding id(96) not supported yet.
        dump: 000002f839cafe00
  Item 2
    Protocol IE: id-RelativeAMFCapacity (86)
      IE length: 1
        decoding id(86) not supported yet.
        dump: ff
  Item 3
    Protocol IE: id-PLMNSupportList (80)
      IE length: 16
        decoding id(80) not supported yet.
        dump: 0002f839000110080102031008112233
[ngap]2020/08/18 19:55:22.943914 example.go:136: write: len 75
`

Thanks

**Comment by hhorai** [comment]
Hi, @regek 

It seems that the amf does not respond to the Initial UE Message from gnbsim.
I think that I can tell you more about it if you provide the full-log output in free5gc including the other NFs.

Thank you,
